//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.CurrencyConverterService")]
    public interface CurrencyConverterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CurrencyConverterService/GetData", ReplyAction="http://tempuri.org/CurrencyConverterService/GetDataResponse")]
        string GetData(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CurrencyConverterService/GetData", ReplyAction="http://tempuri.org/CurrencyConverterService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CurrencyConverterService/GetUsd", ReplyAction="http://tempuri.org/CurrencyConverterService/GetUsdResponse")]
        string GetUsd(double curr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CurrencyConverterService/GetUsd", ReplyAction="http://tempuri.org/CurrencyConverterService/GetUsdResponse")]
        System.Threading.Tasks.Task<string> GetUsdAsync(double curr);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CurrencyConverterServiceChannel : CurrencyClient.ServiceReference1.CurrencyConverterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CurrencyConverterServiceClient : System.ServiceModel.ClientBase<CurrencyClient.ServiceReference1.CurrencyConverterService>, CurrencyClient.ServiceReference1.CurrencyConverterService {
        
        public CurrencyConverterServiceClient() {
        }
        
        public CurrencyConverterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CurrencyConverterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyConverterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyConverterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(string value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(string value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string GetUsd(double curr) {
            return base.Channel.GetUsd(curr);
        }
        
        public System.Threading.Tasks.Task<string> GetUsdAsync(double curr) {
            return base.Channel.GetUsdAsync(curr);
        }
    }
}
